### ISSUE TITLE
uPortal messaging as a Soffit?

### ISSUE THREAD

**Issue by ChristianMurphy** [UW-Madison-DoIT/uportal-messaging#6]
Annotating the Spring boot application as a Soffit could help simplify the integration process with uPortal 4.3+.
https://jasig.github.io/uPortal/developer/soffits/

/cc @drewwills

**Comment by ChristianMurphy** [comment]
Thoughts @Doug-Reed @vertein?

**Comment by drewwills** [comment]
Well, yes & no @vertein.

The soffit solution was originally an answer to the issue of "we don't want to write portlets any more, but we still want a pluggable way to inject DOM fragments into the original page from the portal server every time it changes."  That concept -- pluggable DOM fragments in the portal-rendered page -- is interesting to some, but appears to be far from universally interesting.

That's a bit of a mess, unfortunately.  We used to have a standards-based way to share UI widgets across portal adoptions that was front-end tech agnostic.  It's a valuable thing to have.  A minority of uPortal adopters approach the portal as an opportunity to build something -- they want an ecosystem of contributed modules that work together out-of-the-box.

Recently we have started talking about proxying other kinds of requests (beyond requests for DOM fragments) through the soffit tech.  You could return JSON from a REST API (or perhaps something like a JS bundle) and have very simple access to user contextual info and portal metadata, packaged with the request by the portal.

**Comment by apetro** [comment]
While `uportal-messaging` is uPortal in the sense that it aspires to be a microservice for use with `uPortal-home` to implement "message" (announcement and notification) sourcing and wrangling in a more sophisticated, server-side way, maybe there's nothing tightly coupled to uPortal or uPortal-home about it?

I'd be open to adding a Soffit angle here right at the point that someone is prepared to adopt that Soffit in their uPortal. Until then, I don't think introducing a uPortal tech dependency here is justified.

**Comment by ChristianMurphy** [comment]
https://github.com/Jasig/uPortal/pull/1162 Adds open ID connect as a flexible way for uPortal to share authentication and some metadata with microservices.
